### ISSUE TITLE
Users from Ukraine at d.org sync.

### ISSUE THREAD

**Issue by anpolimus** [drupal-ukraine/ppdorg#66]
Write script that will sync all Ukrainian users at d.org and add new users to ppdorg with statistic data.

**Comment by podarok** [comment]
- add all Ukrainian users
- add companies list
- companies as groups and stats by companies

**Comment by Sanchiz** [comment]
As feature:
- count of commits
- count of posts
- count of documentation?

Maybe we can use "Statistics" module or something like think, to save statistic for certain day/month/year. In this case we can build graphs and fancy reports.

**Comment by podarok** [comment]
@Sanchiz we are already using graph for displaying users activity within ppdorg codebase

**Comment by Sanchiz** [comment]
:+1:

**Comment by anpolimus** [comment]
It seems to me that this issue could be closed already.

**Comment by anpolimus** [comment]
Issue is fixed.
