### ISSUE TITLE
Create a users list entity and configuration for it.

### ISSUE THREAD

**Issue by anpolimus** [drupal-ukraine/ppdorg#72]
Create an object group that will define a group of users that we need to calculate and merge their statistic.
Initial target for us is to create:
- list of users with country=Ukraine;
At current arch. the best way is to implement new taxonomy vocavulary with fields:
- title (title of the group);
- parameters arguments (key-value multivalue field)
  For example:
  field_sex : male
  field_country : Ukraine
  That would be transformed to https://www.drupal.org/api-d7/user.json?field_country=Ukraine&field_sex=1

This structure will give us ability to create different lists for reports like:
Ukraine community with world community
Ukraine vs USA

Also, this project could be reused by other communities around the world.
And this project could be published not just at github but also at distribution sections of d.org as a separate project.

We will use this Vocabulary for creating Drupalers from Ukraine report.
And then we will create and publish another report, based on group with users that marked themselves as a part of DrupalUA company at marketplace.

**Comment by podarok** [comment]
@anpolimus have a look at http://dgo.to/properties module

**Comment by anpolimus** [comment]
@podarok please review. Is it sufficient arch. approach?

**Comment by podarok** [comment]
parameters would be better to build on taxonomy

**Comment by podarok** [comment]
Looks good for me. Let's implement it @anpolimus

**Comment by anpolimus** [comment]
got it.

**Comment by anpolimus** [comment]
@podarok  Could be closed?
