### ISSUE TITLE
Calculate empty profiles.

### ISSUE THREAD

**Issue by anpolimus** [drupal-ukraine/ppdorg#80]
Calculate profiles that dont have:
- posts, commits
- contribute information
and mark them as "empty"

Empty - should be logical field.
It will help us to calculate stat more quickly for active users.

Empty recalculation could be run once per week.

**Comment by podarok** [comment]
due to architecture we can't do that before scanning a profile

**Comment by anpolimus** [comment]
Issue is fixed.
Empty profiles now are calculated and displayed at statistics block.
http://screencloud.net/v/oqY3
