### ISSUE TITLE
Event CT.

### ISSUE THREAD

**Issue by anpolimus** [drupal-ukraine/ppdorg#96]
We have to add event CT for displaying it at the community timeline.
Possible examples that could be defined as event:
- cafe code sprint;
- compay code sprint;
- camp code sprint;
- weekend code sprint;
- Dries birthday;
- celebration parties

This CT should be implemented with next fields:

- title;
- place;
- body;
- date (with finish date);

CT settings should be packed to the feature.

**Comment by andriyun** [comment]
Propositions:
1. Add event type field with options:
- cafe code sprint;
- compay code sprint;
- camp code sprint;
- weekend code sprint;
- Dries birthday;
- celebration parties
2. Amount of attendees
3. Related links for announce, reports, photos

**Comment by anpolimus** [comment]
done
